pacamellar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('', include('services.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

profiles/urls.py
from django.urls import path

from .views import registrar_user, login_user

urlpatterns = [
    path('', registrar_user, name='register_user'),
    path('login_user/', login_user, name='login_user')
]

profiles/forms.py
from django import forms

from .models import Employee, Employer, Skill, DocumentType, City
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    CHOICES = [("1", 'Empleado'), ("2", 'Empleador')]

    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    document_type = forms.ModelChoiceField(queryset=DocumentType.objects.all(), widget=forms.Select(attrs={'class': 'form-control','style':'padding-bottom: 0px;padding-top: 0px;'}))
    document_number = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email= forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # qualification = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    city = forms.ModelChoiceField(queryset=City.objects.all(), widget=forms.Select(attrs={'class': 'form-control mb-3', 'style':'padding-bottom: 0px;padding-top: 0px;'}))
    skill= forms.ModelChoiceField(queryset=Skill.objects.all(), widget=forms.Select(attrs={'class': 'form-control','style':'padding-bottom: 0px;padding-top: 0px;'}))
    user_name= forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    option = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['name', 'lastname', 'document_type', 'document_number', 'age', 'phone_number', 'email', 'city', 'skill','user_name','password1', 'password2', 'option']

    def save(self, commit=True):
        new_user=User.objects.create_user(
            username=self.cleaned_data["user_name"],
            password=self.cleaned_data['password1']
        )
        if self.cleaned_data['option']== "1":
            new_empleado=Employee.objects.create(
                user=new_user,
                name=self.cleaned_data["name"],
                lastname=self.cleaned_data["lastname"],
                document_type=self.cleaned_data["document_type"],
                document_number=self.cleaned_data["document_number"],
                age=self.cleaned_data["age"],
                phone_number=self.cleaned_data["phone_number"],
                city=self.cleaned_data["city"],
                skill=self.cleaned_data["skill"],
                email=self.cleaned_data["email"],
            )
        else:
            new_empleador=Employer.objects.create(
                user=new_user,
                name=self.cleaned_data["name"],
                lastname=self.cleaned_data["lastname"],
                document_type=self.cleaned_data["document_type"],
                document_number=self.cleaned_data["document_number"],
                age=self.cleaned_data["age"],
                phone_number=self.cleaned_data["phone_number"],
                city=self.cleaned_data["city"],
                email=self.cleaned_data["email"],
            )

templates/components/banner.html
<section id="home" style="background: #0dcaf0;">

    <div class="container">

        <div class="row">

            <!-- Introduction -->

            <div class="col-md-6 caption">

                <h1>Bienvenido a PA' CAMELLAR</h1>

                <h2>
                    ¡Estamos pa' ti!

                    </h2>

                <p>Si eres una persona la cual posee grandes habilidades en un área y te encuentras desempleado,
                        esta app es para ti... Puedes hacer un anuncio de tu habilidad.
                        Por el contrario, si eres una persona con una necesidad, también puedes publicarla y te será
                        resuelto con ayuda de nuestros asociados.
                        Pa' camellar es tu ayuda eficaz!!</p>

            </div>

            <!-- Sign Up -->
{#            {% block signup %}#}
{#                hOLA#}
{#            {% endblock %}#}


        </div>

    </div>

</section>

templates/components/footer.html
<footer>

    <div class="container">

        <div class="row">

            <div class="footer-caption col-12">

                <img src="static/assets/img/logo.png" class="img-responsive center-block" alt="logo">

                <hr>

                <h5 class="text-center">Equipo 7, &copy;2022 All rights reserved</h5>

{#                <ul class="liste-unstyled pull-right">#}
{##}
{#                    <li><a href="#facebook"><i class="fa fa-facebook"></i></a></li>#}
{##}
{#                    <li><a href="#twitter"><i class="fa fa-twitter"></i></a></li>#}
{##}
{#                    <li><a href="#linkedin"><i class="fa fa-linkedin"></i></a></li>#}
{##}
{#                    <li><a href="#instagram"><i class="fa fa-instagram"></i></a></li>#}
{##}
{#                </ul>#}

            </div>

        </div>

    </div>

</footer>

templates/components/home.html
<!--========================================

       Services

========================================-->



<section id="services" class="section-padding">

    <div class="container">

        <h2>Nuestros Servicios</h2>

        <p>En cada servicio brindamos calidad y confianza a nuestros usuarios.</p>

        <div class="row">

            <div class="col-md-3">

                <div class="icon-box">

                    <i class="material-icons">thumb_up</i>

                    <h4>Gran Calidad</h4>

                    <p>Comprometidos con mantenernos en los más altos estandares de calidad.</p>

                </div>

            </div>

            <div class="col-md-3">

                <div class="icon-box">

                    <i class="material-icons">euro_symbol</i>

                    <h4>Los mejores precios</h4>

                    <p>Tenemos los mejores precios que puedas encontrar en el mercado.</p>

                </div>

            </div>

            <div class="col-md-3">

                <div class="icon-box">

                    <i class="material-icons">forum</i>

                    <h4>Soporte 24/7</h4>

                    <p>En todo momento estamos disponibles para resolver sus inconvenientes e inquietudes.</p>

                </div>

            </div>

            <div class="col-md-3">

                <div class="icon-box">

                    <i class="material-icons">view_carousel</i>

                    <h4>Diseño UX/UI</h4>

                    <p>Nuestra plataforma brinda la mejor experiecia a nuestros usuarios.</p>

                </div>

            </div>

        </div>

    </div>

</section>


<!--========================================

       Team

========================================-->



<section id="team" class="section-padding">

    <div class="container">

        <h2>Equipo de Profesionales</h2>

        <p>Excelentes desarrolladores pertenecientes al CAR IV, grupo 7 del curso Django básico</p>

        <div class="row">

            <div class="col-md-6 col-lg-4">

                <!--**Team-Member**-->

                <div class="thumbnail team-member">

                    <img src="static/assets/img/team-1.jpg" class="img-responsive img-circle" width="150px" height="150px"  alt="team-1">

                    <div class="caption">

                        <h4>Angélica Morales</h4>

                        <h6>Developer</h6>

                        <p>Desarroladora web especializada en el framework Django y la biblioteca react de JS</p>

                        <hr>

                        <div class="team-social">

                            <ul class="liste-unstyled">

                                <li><a href="#facebook"><i class="fa fa-facebook"></i></a></li>

                                <li><a href="#twitter"><i class="fa fa-twitter"></i></a></li>

                                <li><a href="#linkedin"><i class="fa fa-linkedin"></i></a></li>

                                <li><a href="#instagram"><i class="fa fa-instagram"></i></a></li>

                            </ul>

                        </div>

                    </div>

                </div>

            </div>

            <div class="col-md-6 col-lg-4">

                <!--**Team-Member**-->

                <div class="thumbnail team-member">

                    <img src="static/assets/img/team-2.jpg" class="img-responsive img-circle" width="150px" height="150px"  alt="team-2" style="">

                    <div class="caption">

                        <h4>Juan S. Sierra</h4>

                        <h6>Developer</h6>

                        <p>Encuentro interés en temas relacionado al desarrollo web, inteligencia artificial y robótica.</p>

                        <hr>

                        <div class="team-social">

                            <ul class="liste-unstyled">

                                <li><a href="#facebook"><i class="fa fa-facebook"></i></a></li>

                                <li><a href="#twitter"><i class="fa fa-twitter"></i></a></li>

                                <li><a href="#linkedin"><i class="fa fa-linkedin"></i></a></li>

                                <li><a href="#instagram"><i class="fa fa-instagram"></i></a></li>

                            </ul>

                        </div>

                    </div>

                </div>

            </div>

            <div class="col-md-6 col-lg-4">

                <!--**Team-Member**-->

                <div class="thumbnail team-member">

                    <img src="static/assets/img/team-3.jpg" class="img-responsive img-circle" width="150px" height="150px"  alt="team-3">

                    <div class="caption">

                        <h4>Jair Calderón</h4>

                        <h6>Developer</h6>

                        <p>Apasionado por la tecnología y el desarrollo de software con Python y Django.</p>

                        <hr>

                        <div class="team-social">

                            <ul class="liste-unstyled">

                                <li><a href="#facebook"><i class="fa fa-facebook"></i></a></li>

                                <li><a href="#twitter"><i class="fa fa-twitter"></i></a></li>

                                <li><a href="#linkedin"><i class="fa fa-linkedin"></i></a></li>

                                <li><a href="#instagram"><i class="fa fa-instagram"></i></a></li>

                            </ul>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</section>


<!--========================================

       Contact

========================================-->



<section id="contact" class="section-padding">

    <div class="container">

        <h2>Contáctenos</h2>

    </div>

    <!-- Contact Info -->

    <div class="container contact-info">

        <div class="row">

            <div class="col-md-4">

                <div class="icon-box">

                    <i class="material-icons">place</i>

                    <h4>Dirección</h4>

                    <p>Cartagena: Cll. 32 #23-13 Edf. Banco Popular of. #702</p>

                </div>

            </div>

            <div class="col-md-4">

                <div class="icon-box">

                    <i class="material-icons">phone</i>

                    <h4>Llámenos al</h4>

                    <p>301-485-6897</p>

                    <p>305-916-4578</p>

                </div>

            </div>

            <div class="col-md-4">

                <div class="icon-box">

                    <i class="material-icons">email</i>

                    <h4>Envíenos un Correo</h4>

                    <p>kpalacios@gmail.com</p>

                    <p>lmercado@gmail.com</p>

                </div>

            </div>

        </div>

    </div>

    <!-- Google Map -->

    <div id="map"></div>

    <!-- Contact Form -->

{#    <div class="contact-forms">#}
{##}
{#        <div class="container">#}
{##}
{#            <h2>Drop us a Line</h2>#}
{##}
{#            <form class="contact-form">#}
{##}
{#                <div class="col-md-6">#}
{##}
{#                    <div class="form-group">#}
{##}
{#                        <input type="text" class="form-control" placeholder="Full Name" required="required">#}
{##}
{#                    </div>#}
{##}
{#                    <div class="form-group">#}
{##}
{#                        <input type="email" class="form-control" placeholder="Email" required="required">#}
{##}
{#                    </div>#}
{##}
{#                </div>#}
{##}
{#                <div class="col-md-6">#}
{##}
{#                    <div class="form-group">#}
{##}
{#                        <textarea class="form-control" rows="3" placeholder="Message"></textarea>#}
{##}
{#                    </div>#}
{##}
{#                </div>#}
{##}
{#                <button type="submit" class="btn btn-blue">Send Message</button>#}
{##}
{#            </form>#}
{##}
{#        </div>#}
{##}
{#    </div>#}

</section>

templates/components/item.html
{% block content %}

<div class="col-6 mb-4 ">
    <div class="card text-center mx-4">
      <div class="card-header">
        {% if item.employee %}
            Publicado por: {{ item.employee }}
        {% else %}
            Publicado por: {{ item.employer }}
        {% endif %}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <p class="card-text">{{ item.description }}</p>

        {% if item.employee %}

            <p class="card-text">Habilidades: {{ item.skill }}</p>
            <a href="{% url 'edit_advertisement' item.id %}" class="btn btn-primary">Editar</a>
            <a href="{% url 'delete_advertisement' item.id %}" class="btn btn-danger">Eliminar</a>

        {% else %}

            <p class="card-text">Habilidades necesarias: {{ item.skill }}</p>
            <p class="card-text">Remuneración: ${{ item.remuneration }}</p>
            <p class="card-text">Tiempo requerido: {{ item.time_lapse }} weeks</p>

            <a href="{% url 'edit_necessity' item.id %}" class="btn btn-primary">Editar</a>
            <a href="{% url 'delete_necessity' item.id %}" class="btn btn-danger">Eliminar</a>

        {% endif %}

      </div>
      <div class="card-footer text-muted">
        Hace 2 días
      </div>
    </div>
</div>
{% endblock %}

templates/components/navbar.html
{% load static %}

  <nav class="navbar navbar-default navbar-fixed white bootsnav navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000" style="margin-bottom: 0px;">

    <div class="container">

        <!-- Start Header Navigation -->

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">

                <i class="fa fa-bars"></i>

            </button>

            <a class="navbar-brand" href="#brand">

                <img src="{% static 'assets/img/logo.png' %}" class="logo" alt="logo">

            </a>

        </div>

        <!-- End Header Navigation -->



        <!-- Collect the nav links, forms, and other content for toggling -->

        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="nav navbar-nav navbar-right">

                <li class=""><a href="{% url 'home' %}">Home</a></li>

                <li class=""><a href="{% url 'home' %}#services ">Servicios</a></li>

                <li class=""><a href="{% url 'home' %}#team ">Equipo</a></li>

                <li class=""><a href="{% url 'home' %}#contact" >Contacto</a></li>

                {% if request.user.is_authenticated %}
                    <li class=""><a href="{% url 'necessities_list' %}#necessities">Necesidades</a></li>

                    <li class=""><a href="{% url 'advertisements_list' %}#advertisements">Anuncios</a></li>

                    <li class=""><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% endif %}

            {% if not request.user.is_authenticated %}
                <li class="button-holder">

                    <button type="button" class="btn btn-blue navbar-btn" data-toggle="modal" data-target="#SignIn">Iniciar Sesión</button>

                </li>
            {% endif %}

            </ul>

        </div>

        <!-- /.navbar-collapse -->

    </div>

</nav>

templates/components/sign_up_form.html
{% if not request.user.is_authenticated %}

    <div class="col-md-5 col-md-offset-1">

        <form class="signup-form" method="POST" action="{% url 'register_user' %}">

            {% csrf_token %}
            <span class="help-block" style="color:red">{{ form.errors.password }}</span>

            <h2 class="text-center">Regístrese Ahora</h2>

            <hr>

             <div class="form-group">

                <input type="text" class="form-control" placeholder="Name" required="required" id="id_name" name="name">

            </div>
            <div class="form-group">

                <input type="text" class="form-control" placeholder="Last Name" required="required" id="id_lastname" name="lastname">

            </div>
             <div class="form-group">
                 <option selected>Tipo de documento</option>
                {{ form.document_type }}
            </div>
            <div class="form-group">

                <input type="number" class="form-control" placeholder="Número de documento" required="required" id="id_document_number" name="document_number">

            </div>
            <div class="form-group">

                <input type="number" class="form-control" placeholder="Edad" required="required" id="id_age" name="age">

            </div>
            <div class="form-group">

                <input type="text" class="form-control" placeholder="Número de teléfono" required="required" id="id_phone_number" name="phone_number">

            </div>

            <div class="form-group">

                <input type="email" class="form-control" placeholder="Corre electrónico" required="required" id="id_email" name="email">

            </div>
    {#                        <div class="form-group">#}
    {#                            <select class="form-select form-select mb-5 form-control" aria-label=".form-select example"#}
    {#                                    style="padding-bottom: 0px;padding-top: 0px; " id="id_city" name="city">#}
    {#                                <option selected>Seleccione ciudad</option>#}
    {#                                <option value="1">City 1</option>#}
    {#                                <option value="2">City 2</option>#}
    {#                            </select>#}
    {#                        </div>#}

            <div class="form-group">
                <option selected>Seleccione ciudad</option>
               {{ form.city}}
            </div>

            <div class="form-group">

                <input type="text" class="form-control" placeholder="Nombre de usuario" required="required" id="id_user_name" name="user_name" >

            </div>

            <div class="form-group">

                <input type="password" class="form-control" placeholder="Contraseña" required="required"  name="password1" id="id_password1" >

            </div>
            <div class="form-group">

                <input type="password" class="form-control" placeholder="Confirme su contraseña" required="required"  name="password2" id="id_password2" >

            </div>


            <div class="form-group">
                <select class="form-select form-select mb-5 form-control" aria-label=".form-select example"
                        style="padding-bottom: 0px;padding-top: 0px; " id="id_option" name="option">
                    <option selected>Seleccione rol</option>
                    <option value="1">Empleado</option>
                    <option value="2">Empleador</option>
                </select>

            </div>
              <div class="form-group">
                  <option selected>Habilidad</option>
                  {{ form.skill }}
            </div>

            <div class="form-group text-center">

                <button type="submit" class="btn btn-blue btn-block">Start Now</button>

            </div>

        </form>

    </div>

{% endif %}